[package]
name = "neptunics"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
crossterm = "0.28.1"
icalendar = { version = "0.16.11", features = ["chrono-tz"] }
ratatui = "0.29.0"
unicode-segmentation = "1.12.0"
